### ISSUE TITLE
Translation of Clips on icon hover

### ISSUE THREAD

**Issue by migmake** [carlcs/craft-redactoriconbuttons#1]
Is it an issue for you here or for pixelandtonic/RedactorClips ??
Not sure....

On hover
![screen shot 2016-07-26 at 10 44 06](https://cloud.githubusercontent.com/assets/3531623/17131476/eb11940c-531d-11e6-84e0-a92fd32e671f.jpg)

**Comment by carlcs** [comment]
It's for the RedactorClips plugin.
